app/layout.tsx
components/combobox-area.tsx
components/map-dashboard.tsx
components/ui/sonner.tsx
lib/data.ts
lib/utils.ts
package-lock.json
package.json

Currently, the API throws error when the response of data fetching does not successful (200 OK) and that error doesn't show up on the UI (only logged in console).
- The API now returns valid response (object, not throw error) even if the data fetching does not successful (200 OK).
- Use `toast` to show the error in the UI.
- Refactor the `ComboboxArea` and `MapDashboard`.
None

Show the error when failed fetch data

---

components/ui/command.tsx

Issue Number: 
- https://github.com/pacocoursey/cmdk/issues/189
- https://github.com/pacocoursey/cmdk/issues/212
Error when the `value` of  `CommandItem` component contains quotes `"`.
`CommandItem` component is a Ref component from [`cmdk`](https://github.com/pacocoursey/cmdk)'s `Command.Item` component.
Escape all quotes `"` in `value` as a temporary fix.
Revert this changes when the issues are closed (fixed), and upgrade the `cmdk` dependency.

fix quotes `"` issue in `CommandItem` component

---

components/combobox.tsx
components/geojson-area.tsx
components/map-dashboard.tsx

Currently, when an area is selected, user need to drag (and zoom) the map to see the area clearly by itself.
- Now, the map will fly (move and zoom) to the selected area automatically.
- Change the show/hide boundary feature (now only change the boundary color to hide it, it doesn't removed from the components hierarchy).
- Disable the child's ComboboxArea when the boundary data of its parent is loading.
- Show loading spinner besides the boundary switch, when the boundary data is …

Map fly to selected area

---

app/(main)/[code]/error.tsx
app/(main)/[code]/page.tsx
app/(main)/layout.tsx
components/geojson-area.tsx
components/map-dashboard.tsx
components/ui/alert-dialog.tsx
lib/utils.ts
package-lock.json
package.json

Add detail area page `/{code}` and auto-select the suitable area.
For example, `/31.71.01` will auto-select `Gambir` district and its parents.
None

Add detail area page `/{code}`

---

components/map-dashboard.tsx

When the sidebar panel is resized, the map does not resize accordingly.
Make the map resize dynamically to match the changes in the sidebar panel's size.
None

fix: resize the map when the sidebar panel is resized

---

components/map-dashboard.tsx
hooks/useDoubleTap.ts

Users on touch devices are unable to collapse or expand the sidebar because double-click functionality is not commonly supported on these devices.
This PR adds the ability to collapse or expand the sidebar panel by double-clicking or double-tapping the sidebar toggle. It introduces a new hook called `useDoubleTap`, which triggers a callback function on a double-tap event.
This allows users to collapse or expand the sidebar panel by double-tapping on **touch devices**.
None

feat: add double-tap functionality to collapse/expand the sidebar

---

app/api/[area]/[code]/boundary/route.ts
lib/data.ts

This pull request includes updates to handle responses more consistently by using `NextResponse` instead of `Response` across multiple files.
The main changes involve importing `NextResponse` and replacing instances of `Response` with `NextResponse`.
None

refactor: use `NextResponse` instead of `Response`

---

app/globals.css
components/map-dashboard.tsx

Map components styles like popup and zoom control weren't changes when dark mode active. Some components like the number of the island marker also less visible in dark mode.
This pull request includes changes to the `app/globals.css` and `components/map-dashboard.tsx` files to improve the styling of map elements and update the text styling for better consistency.
Styling improvements:
* `app/globals.css`: Added custom styles to override default Leaflet styles, including popups, markers, …

Implement dark mode for leaflet components

---

components/navbar.tsx

Issue Number: *N/A*
*Hyperlink on the navbar replacing the URL address on the current tab*
*I added target _blank to open the link on the new tab instead of replacing the current tab*
*none*

fix: added target blank instead of replacing current tab

---

lib/utils.ts
modules/MapDashboard/AreaSelectors.tsx

- Not all **provinces** are loaded in Provice selector (only load 10 provinces).
This pull request introduces a new utility function and refactors the `AreaSelectors` component to improve code readability and maintainability. The most important changes include adding the `objectFromEntries` function and refactoring the `query` state initialization in `AreaSelectors`.
* [`lib/utils.ts`](diffhunk://#diff-98e56006aa8453a29bc2b8bc8e6f718b3f17ba66470f3a52a5dc5bd643482e70R15-R20): Added the …

fix: not all provinces data loaded in `AreaSelectors`

---

modules/MapDashboard/AreaBoundary.tsx
modules/MapDashboard/IslandMarkers.tsx

Map icon in `IslandMarkers` is too big.
This pull request includes several changes to the `MapDashboard` module, specifically to the `AreaBoundary` and `IslandMarkers` components. The changes primarily involve modifying the class properties of SVG icons to ensure consistent sizing.
Improvements to SVG icon sizing:
* [`modules/MapDashboard/AreaBoundary.tsx`](diffhunk://#diff-62415af83360317764cf5bd12df47845abdc21b0615bf15144187a77dfb36491L178-R180): Updated the `LinkIcon` and `MapIcon` …

Adjust icon sizes and spacing in AreaBoundary and IslandMarkers

---

app/globals.css
components/map.tsx
components/tile-layer.tsx
package.json
pnpm-lock.yaml
public/map-styles/dark.json
public/map-styles/light.json

Currently, the map experiences lag when dragged on mobile devices with dark mode enabled. The primary cause of this lag is the implementation of dark mode using Tailwind CSS on the map tiles. This setup requires each tile to undergo additional processing to apply the dark theme, resulting in delays that impact performance, especially on mobile.
This pull request includes significant changes to the map component and its dependencies, focusing on improving the map rendering and theming …

Fix Laggy Map Dragging on Mobile with Dark Mode Enabled

---

components/area-boundary.tsx
modules/MapDashboard/BoundaryLayers.tsx
modules/MapDashboard/PopupArea.tsx
modules/Pilkada2024/BoundaryLayers.tsx

`AreaBoundary` component use `useArea` hook to fetch the data and provide `render` property to render the children based on its data. But this behavior is unnecessary because in some cases, the data for the children has been fetched in somewhere else.
This behavior can leads to **Throttle Error: Too Many Request** since the [idn-area API](https://github.com/fityannugroho/idn-area) has request limits.
- Removing the `render` prop
- Directly using the `useArea` hook within components to fetch data.
**Key changes include:**
* [`components/area-boundary.tsx`](diffhunk://#diff-fcba0a1ff0012ded25e17ce6 …

Simplify `AreaBoundary`, prevent unnecessary `useArea` usage

---

components/ComboboxArea.tsx
modules/MapDashboard/AreaSelectors.tsx
modules/Pilkada2024/Sidebar.tsx

Currently `ComboboxArea` component depends to the `useMapDashboard` hook to handle the selected option, so that it must be implemented under `MapDashboardProvider` only.
- Untied `ComboboxArea` component dependence to the `useMapDashboard` hook. Replace it with inner `useState`.
- Apply `useMemo` to memoize the options.
- Remove properties override for `autoClose` and `fullWidth`. Now it must be set explicitly.
- Move `ComboboxArea.tsx` file to `components` directory.

refactor: make `ComboboxArea` component reusable

---

modules/MapDashboard/PopupArea.tsx

The popup tip position is in center. See the picture below:
This pull request includes updates to the `PopupArea` component in `modules/MapDashboard/PopupArea.tsx` to improve the styling consistency by replacing the `text-gray-500` class with the `text-muted-foreground` class.
Styling updates:
* Updated the "Loading..." message inside `BasePopupArea` to use the `text-muted-foreground` class for consistent styling and added a `mx-auto` class for centering.
* Replaced the `text-gray-500` class with `text-muted-foreground` for parent labels in the popup to align with the updated design language.

fix: popup tip position and change the text color

---

lib/data.ts
modules/MapDashboard/IslandMarkers.tsx
modules/MapDashboard/IslandsInfo.tsx
modules/MapDashboard/hooks/__tests__/useIslands.test.tsx
modules/MapDashboard/hooks/useIslands.ts

Ensure islands that are not assigned to any regency are loaded and displayed on the map. Also improve island marker rendering, clustering behavior, and popup content to make islands more discoverable and metadata more accurate.
- Fix loading logic so islands without a matching regency are included in the dataset and map layer.
- Improve island marker styling and clustering so markers remain visible and clustered sensibly across zoom levels.
- Fix popup / IslandsInfo content to show correct island metadata and clearer labels.
- Minor code cleanup and linting on island-related components.
- modules/MapDashboard/IslandMarkers.tsx
- modules/MapDashboard/IslandsInfo.tsx
- modules/MapDashboard/MapView.tsx
- components/MapMarkerClusterGroup.tsx

fix(islands): load islands that do not belong to any regency

---

components/MapMarker.tsx
package.json
pnpm-lock.yaml

- components/MapMarker.tsx
- Make marker asset imports robust to both Next import shapes: string (Turbopack) and object with `.src` (Webpack). Use `typeof markerIcon === 'string' ? markerIcon : markerIcon.src` for `iconUrl`, `iconRetinaUrl`, and `shadowUrl`.
- Prevents runtime error: `iconUrl not set in Icon options` when running under `next dev --turbo`.
- package.json
- Add dependency: `keyv@4.5.4`.
- Fixes bundling error from dynamic adapter resolution in `keyv` used transitively by `cacheable-request`/`got`/`staticmaps` when building server components: `Module not found: Can't resolve ('@keyv/redis' | ... | <dynamic>)`.
- Next/Turbopack returns imported static assets differently than Webpack. The MapMarker change ensures a valid URL is always passed to Leaflet regardless of bundler.
- …

fix: support Turbopack asset imports for Leaflet markers + add keyv dependency

---

components/ComboboxArea.tsx
modules/MapDashboard/AreaSelectors.tsx

This PR fixes the area selector behavior by passing the currently selected area into the Combobox on mount.
- components/ComboboxArea.tsx: add `defaultSelected` prop and initialize internal `selectedArea` state from it.
- modules/MapDashboard/AreaSelectors.tsx: pass `selectedArea[area]` as `defaultSelected` to `ComboboxArea`.
Previously the combobox did not reflect the existing selection when the selector UI mounted. This ensures the UI shows the current selection immediately.
1. Open the map dashboard and verify the area comboboxes display the currently selected area.
2. Select a different area and ensure linked child selectors update.
Checklist:

fix: initialize `ComboboxArea` with default selected area

---

components/Map.tsx

This pull request fixes a regression where the map's forwarded ref was not properly passed through `components/Map.tsx`, which caused downstream consumers relying on the `mapRef` to fail (e.g. fly-to/bounds operations and map resize handler).
- Ensure the `MapContainer` receives the forwarded `ref` so external code can access the Leaflet map instance reliably.
- Small defensive change so map initialization is more robust during client hydration.
- The regression was introduced by changes in PR #59 which modified component initialization/prop handling and indirectly surfaced the missing ref forwarding in `components/Map.tsx`. This PR corrects that by forwarding the ref to `MapContainer`.

fix: ensure MapContainer receives forwarded ref

---

components/ComboboxArea.tsx
modules/MapDashboard/AreaSelectors.tsx
modules/MapDashboard/BoundarySettings.tsx
modules/MapDashboard/IslandMarkers.tsx
modules/MapDashboard/IslandsInfo.tsx
modules/MapDashboard/Sidebar.tsx
modules/Pilkada2024/Sidebar.tsx

This PR merges `fix-area-selector` into `main` and focuses on fixes and UX improvements around the area selection UI, map integration, and island marker labels. Below is a behavior-focused explanation of what changed and why.
- Added a programmatic reset API so the combobox can be cleared by other UI (for example when changing selection scope), preventing stale selections.
- Initialize `ComboboxArea` with a sensible default when a page expects a starting area to avoid empty or inconsistent UI states on load.
- Updated the combobox placeholder text to be clearer and more actionable.
- Propagated these changes to the Sidebar and the `Pilkada2024` module to ensure consistent selector behaviour across pages.
- Parent/consumer components now call the combobox reset when switching …

fix(area-selector): improve ComboboxArea/reset + UI tweaks

---

README.md
modules/MapDashboard/Dashboard.tsx
modules/MapDashboard/IslandMarkers.tsx
modules/MapDashboard/IslandsFilterProvider.tsx
modules/MapDashboard/IslandsInfo.tsx

This PR adds UI controls and a small context provider to filter island markers on the Map Dashboard. The main goal is to allow users to toggle filters for "Populated" and "Outermost-small" islands and to show/hide island markers entirely. When both filters are active the logic uses OR semantics (show islands that are populated OR outermost-small).
- Added a small provider to manage island filter state and derived values:
- `modules/MapDashboard/IslandsFilterProvider.tsx` — new
- Exposes `filter` ({ populated, outermostSmall }), `setFilter`, `filteredIslands`, `counts`, `isLoading`, `showMarkers`, and `setShowMarkers`.
- Uses the existing `useIslands()` hook to fetch island data and compute derived values.
- Wired the provider into the dashboard root so both the sidebar and map can access …

Add islands filtering controls and show/hide markers
